import { useState } from "react";
import { brokerReportDay, exactTotal, type ReviewFill, type WeeklyReviewInput } from "@invest/domain";
import { CHART_COLORS } from "./PortfolioCharts";
import { fillTime } from "./ExecutionDetails";
import { formatMoney } from "./format";
export function BrokerTradeTimeline({ fills, range }: { fills: ReviewFill[]; range: Pick<WeeklyReviewInput, 'weekStart' | 'weekEnd'> }) {
  const [broker, setBroker] = useState('all');
  const [environment, setEnvironment] = useState('real');
  const selected = fills.filter(f => { const day = brokerReportDay(f.occurredAt); return (f.source === 'ibkr' || f.source === 'tradier') && (environment === 'sandbox' ? f.environment === 'sandbox' : f.environment !== 'sandbox') && day && day >= range.weekStart && day <= range.weekEnd && (broker === 'all' || f.source === broker); }).sort((a, b) => (brokerReportDay(a.occurredAt) ?? '').localeCompare(brokerReportDay(b.occurredAt) ?? '') || a.occurredAt.localeCompare(b.occurredAt));
  const days = [...new Set(selected.map(f => brokerReportDay(f.occurredAt)!))];
  const brokers = ['ibkr', 'tradier'];
  const points = days.flatMap(day => brokers.map(source => ({ day, source, count: selected.filter(f => brokerReportDay(f.occurredAt) === day && f.source === source).length })));
  const max = Math.max(1, ...points.map(p => p.count));
  const totals = [...new Set(selected.map(f => `${f.source}:${f.currency}`))].map(key => { const rows = selected.filter(f => `${f.source}:${f.currency}` === key); return { key, currency: rows[0]!.currency, broker: rows[0]!.source, pnl: exactTotal(rows.map(f => f.realizedPnl)), count: rows.length }; });
  return <figure className="portfolio-chart broker-trade-timeline"><figcaption><div><h3>券商成交日期分布</h3><p className="chart-note">保留各券商原始交易日，未转换跨时区的日期。</p></div><div className="filter-toolbar"><select aria-label="原始成交券商" value={broker} onChange={e => setBroker(e.target.value)}><option value="all">全部券商</option>{brokers.map(b => <option key={b} value={b}>{b.toUpperCase()}</option>)}</select><select aria-label="原始成交环境" value={environment} onChange={e => setEnvironment(e.target.value)}><option value="real">实盘 / 报表</option><option value="sandbox">模拟账户</option></select></div></figcaption>
    {selected.length ? <><svg viewBox="0 0 800 240" role="img" aria-label="按券商和交易日分组的成交笔数柱状图"><text x="20" y="20" className="chart-axis-text">成交笔数</text>{days.map((day, index) => { const center = 80 + index * 640 / Math.max(1, days.length - 1); return <g key={day}><text x={center} y="225" textAnchor="middle" className="chart-axis-text">{day.slice(5)}</text>{brokers.map((source, i) => { const count = points.find(p => p.day === day && p.source === source)!.count, height = count / max * 150; return <g key={source}><rect x={center - 28 + i * 30} y={190 - height} width="24" height={height} rx="3" fill={CHART_COLORS[i]}><title>{day} · {source.toUpperCase()} · {count} 笔成交</title></rect><text x={center - 16 + i * 30} y={182 - height} textAnchor="middle" className="chart-axis-text">{count || ''}</text></g>; })}</g>; })}</svg><div className="line-legend">{brokers.map((b, i) => <button type="button" key={b} onClick={() => setBroker(broker === b ? 'all' : b)}><i style={{ background: CHART_COLORS[i] }} />{b.toUpperCase()}</button>)}</div><div className="tr-stats">{totals.map(t => <div key={t.key}><span>{t.broker.toUpperCase()} · 券商已实现盈亏</span><strong>{formatMoney(t.pnl)} {t.currency}</strong><small>{t.count} 笔成交{t.pnl === null ? ' · 接口未提供完整盈亏字段' : ' · 券商原值，不重复扣佣金'}</small></div>)}</div><div className="position-table-wrap"><table className="position-table"><thead><tr><th>原始成交时间</th><th>券商</th><th>标的 / 买卖</th><th>数量</th><th>成交价</th><th>费用成本</th><th>已实现盈亏</th></tr></thead><tbody>{selected.map(f => <tr key={f.id}><td>{fillTime(f)}</td><td>{f.sourceLabel ?? f.source.toUpperCase()}</td><td>{f.symbol} · {f.side === 'buy' ? '买' : '卖'}</td><td>{f.quantity}</td><td>{f.price ?? '—'} {f.currency}</td><td>{formatMoney(f.feeCost)}</td><td>{formatMoney(f.realizedPnl ?? null)} {f.currency}</td></tr>)}</tbody></table></div></> : <p className="empty-state">此期间没有已同步的券商原始成交。</p>}
    <p className="chart-note">仅展示 API / Flex 同步记录；结单导入留在「复盘档案收益」中，两个视图不相加。Tradier 历史接口未提供逐笔已实现盈亏时显示「—」，不推算为零。</p>
  </figure>;
}
