import { useEffect, useMemo, useRef, useState } from "react";
import { STUDY_INSTRUMENTS, US_STUDY_INDEX_IDS, filterStudyEvents, studyEventComparisonIds, studyEventWindow, type GeoEvent } from "@invest/domain";
import { writeJson } from "./api";
import { StudyCandles, changeText } from "./ResearchCharts";
import type { StudyBoard, StudyData } from "./research-model";

import { ResearchSources } from "./ResearchSources";

const CATEGORIES = { war: "战争、军事与恐袭", sanctions: "制裁", tariff: "关税与贸易", politics: "政局、选举与外交", supply: "航运与供应链", other: "其他地缘冲击" } as const;
const emptyFilters = { year: "", category: "", region: "", query: "" };
const shift = (date: string, n: number) => new Date(Date.parse(date) + n * 86400000).toISOString().slice(0, 10);
export function GeoObservation({ active, board, study, reload, draftDate, initialAsset, focusId }: { active: boolean; board: StudyBoard; study: StudyData; reload: () => Promise<void>; draftDate: { date: string; nonce: number } | null; initialAsset: string; focusId: string | null }) {
  const [edit, setEdit] = useState<Partial<GeoEvent> | null>(null), [selected, setSelected] = useState<string | null>(null), [chartId, setChartId] = useState("sp500"), [error, setError] = useState(""), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const [filters, setFilters] = useState(emptyFilters), [overviewIndex, setOverviewIndex] = useState("sp500");
  const detailRef = useRef<HTMLDivElement>(null);
  const openedDraft = useRef<number | null>(null);
  useEffect(() => { if (draftDate && openedDraft.current !== draftDate.nonce) { openedDraft.current = draftDate.nonce; setEdit({ date: draftDate.date, assetIds: [initialAsset], timing: "unknown", category: "war" }); } }, [draftDate, initialAsset]);
  useEffect(() => { if (focusId) { setSelected(focusId); setFilters(emptyFilters); } }, [focusId]);
  const events = useMemo(() => filterStudyEvents(board.events, filters), [board.events, filters]);
  const years = useMemo(() => [...new Set([...board.events.map(e => e.date.slice(0, 4)), ...Array.from({ length: Math.max(0, new Date().getUTCFullYear() - 2015) }, (_, i) => String(2016 + i))])].sort().reverse(), [board.events]);
  const event = events.find(e => e.id === selected) ?? events[0];
  const comparisons = event ? studyEventComparisonIds(event) : [];
  const selectedChartId = comparisons.includes(chartId) ? chartId : "sp500";
  // Keep demand as an ID key: study and comparisons are recreated on every render.
  // Refill only free slots as shared requests finish; switching views or events
  // discards unstarted demand, while in-flight results remain reusable by ID.
  const demandKey = [...new Set([overviewIndex, ...(event ? [selectedChartId, ...comparisons] : [])])].join(",");
  const { data, errors, busy: loadingIds, load } = study;
  useEffect(() => {
    if (!active) return;
    const available = Math.max(0, 2 - loadingIds.length);
    const missing = demandKey.split(",").filter(id => !data[id] && !errors[id] && !loadingIds.includes(id));
    for (const id of missing.slice(0, available)) void load(id);
  }, [active, demandKey, data, errors, loadingIds, load]);
  const historyState = (id: string) => loadingIds.includes(id) ? "loading" : errors[id] ? "error" : !data[id] ? "pending" : !data[id].bars.length ? "empty" : "ready";
  const historyLabel = (id: string) => ({ loading: "读取中…", error: data[id]?.bars.length ? "读取失败 · 保留已有历史" : "读取失败", pending: "等待自动读取", empty: "来源暂无数据", ready: data[id]?.stale ? "历史缓存已过期" : "历史已就绪" })[historyState(id)];
  const emptyMessage = (id: string) => errors[id] ? "历史读取失败，可重新读取；其他资产继续显示。" : loadingIds.includes(id) ? "正在自动读取日度历史，完成后显示图表与事件标记。" : "历史已加入读取队列，完成后自动显示。";
  const counts = comparisons.reduce((result, id) => { result[historyState(id)]++; return result; }, { loading: 0, error: 0, pending: 0, empty: 0, ready: 0 });
  const retryIds = comparisons.filter(id => historyState(id) === "error" || historyState(id) === "empty");
  const instrument = STUDY_INSTRUMENTS.find(i => i.id === selectedChartId)!;
  const overviewInstrument = STUDY_INSTRUMENTS.find(i => i.id === overviewIndex)!;
  const today = new Date().toISOString().slice(0, 10);
  const loadEvent = async () => { for (const id of retryIds) await study.load(id); };
  const chooseEvent = (e: GeoEvent) => { setSelected(e.id); requestAnimationFrame(() => detailRef.current?.scrollIntoView({ behavior: "smooth", block: "start" })); };
  const download = () => { const url = URL.createObjectURL(new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), filters, events }, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = `geopolitical-events-${filters.year || "all"}.json`; a.click(); URL.revokeObjectURL(url); };
  return <div className="geo-observation"><div className="workspace-intro"><div><p className="eyebrow">EVENT REVIEW · 2016 至今</p><h3>把事件放回发生时的市场</h3><p>选择事件，自动关联五个美股指数与相关资产的历史，查看事实、来源和前后变化。</p></div><button className="primary-button" onClick={() => setEdit({ date: today, category: "war", timing: "unknown", assetIds: ["sp500", "gold-futures", "wti-futures", "us10y"] })}>＋ 标记地缘事件</button></div>
    {error && <p className="inline-error" role="alert">{error}</p>}{notice && <p className="password-success" role="status">{notice}</p>}
    {edit && <form className="research-form study-editor" key={edit.id ?? `${edit.date}-${draftDate?.nonce ?? 0}`} onSubmit={async e => {
      e.preventDefault(); if (busy) return; const f = new FormData(e.currentTarget); const checkedAssets = f.getAll("assetIds").map(String); const assetIds = [...(edit.assetIds ?? []).filter(id => checkedAssets.includes(id)), ...checkedAssets.filter(id => !edit.assetIds?.includes(id))]; setBusy(true); setError("");
      try { const result = await writeJson<{ record: GeoEvent }>(`/api/research/board/events${edit.id ? `/${edit.id}` : ""}`, edit.id ? "PATCH" : "POST", { title: f.get("title"), date: f.get("date"), category: f.get("category"), region: f.get("region"), timing: f.get("timing"), facts: f.get("facts"), mechanism: f.get("mechanism"), sourceUrl: f.get("sourceUrl"), assetIds, sources: edit.sources }); await reload(); setSelected(result.record.id); setFilters(emptyFilters); setEdit(null); setNotice("事件已保存，关联资产的 K 线中会出现标记。"); }
      catch (e) { setError(e instanceof Error ? e.message : "保存失败"); } finally { setBusy(false); }
    }}><h4 className="form-wide">{edit.id ? "编辑事件" : "添加事件标记"}</h4><label className="form-wide">事件标题<input name="title" required maxLength={200} defaultValue={edit.title} /></label><label>事件日期<input type="date" name="date" required defaultValue={edit.date} /></label><label>相对美股收盘时段<select name="timing" defaultValue={edit.timing}><option value="unknown">尚未核实时段</option><option value="before-close">当日收盘前</option><option value="after-close">当日收盘后</option></select></label><label>事件类型<select name="category" defaultValue={edit.category}>{Object.entries(CATEGORIES).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>地区<input name="region" maxLength={100} defaultValue={edit.region} placeholder="涉及国家或地区" /></label><label className="form-wide">已确认事实<textarea required name="facts" maxLength={10000} defaultValue={edit.facts} placeholder="发生了什么？将事实与影响判断分开。" /></label><label className="form-wide">可能传导机制 / 待验证问题<textarea name="mechanism" maxLength={5000} defaultValue={edit.mechanism} placeholder="例如：供应收缩是否抬高能源价格，继而改变通胀和利率预期？" /></label><label className="form-wide">原始来源链接<input type="url" name="sourceUrl" maxLength={2000} defaultValue={edit.sourceUrl} /></label><fieldset className="form-wide study-asset-checks"><legend>关联资产（至少一项）</legend>{STUDY_INSTRUMENTS.map(i => <label key={i.id}><input type="checkbox" name="assetIds" value={i.id} defaultChecked={edit.assetIds?.includes(i.id)} />{i.name}</label>)}</fieldset><div className="form-wide study-actions"><button className="primary-button" disabled={busy}>保存事件</button><button type="button" className="secondary-button" onClick={() => setEdit(null)}>收起</button></div></form>}
    <div className="study-panel study-event-overview">
      <div className="content-heading"><div><h3>美股指数与事件总览</h3><p className="muted">已收录 {board.events.length} 条主要事件 · 当前筛选 {events.length} 条。按日期与五个美股指数统一对照，不表示每条事件都造成显著市场影响。</p></div><button className="text-button" onClick={download}>导出筛选事件</button></div>
      <div className="study-event-filters study-toolbar"><label>年份<select aria-label="事件年份" value={filters.year} onChange={e => setFilters({ ...filters, year: e.target.value })}><option value="">全部年份</option>{years.map(year => <option key={year} value={year}>{year} · {board.events.filter(e => e.date.startsWith(year)).length} 条</option>)}</select></label><label>事件类型<select aria-label="事件类型筛选" value={filters.category} onChange={e => setFilters({ ...filters, category: e.target.value })}><option value="">全部类型</option>{Object.entries(CATEGORIES).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>国家或地区<input aria-label="事件地区筛选" value={filters.region} onChange={e => setFilters({ ...filters, region: e.target.value })} placeholder="例如：伊朗、欧洲" /></label><label>检索事件<input aria-label="检索地缘事件" value={filters.query} onChange={e => setFilters({ ...filters, query: e.target.value })} placeholder="标题、事实或机制…" /></label><button className="text-button" onClick={() => setFilters(emptyFilters)}>清除事件筛选</button></div>
      <div className="study-toolbar"><label>对照指数<select aria-label="地缘总览指数" value={overviewIndex} onChange={e => setOverviewIndex(e.target.value)}>{US_STUDY_INDEX_IDS.map(id => <option key={id} value={id}>{STUDY_INSTRUMENTS.find(i => i.id === id)!.name}</option>)}</select></label><button className="secondary-button" disabled={!!study.busy.length} onClick={() => void study.load(overviewIndex)}>{study.busy.includes(overviewIndex) ? "读取中…" : "重新读取指数历史"}</button><span className="muted">{filters.year || "2016 至今"} · 点击图中标记选择事件</span></div>
      {study.errors[overviewIndex] && <p className="inline-error" role="alert">{study.errors[overviewIndex]}</p>}
      <StudyCandles key={`overview-${overviewIndex}-${filters.year}`} instrument={overviewInstrument} series={study.data[overviewIndex]} from={`${filters.year || "2016"}-01-01`} through={filters.year ? `${filters.year}-12-31` : today} events={events} onEvent={chooseEvent} initialInterval={filters.year ? "day" : "month"} initialCount={500} emptyMessage={emptyMessage(overviewIndex)} />
      <p className="chart-note">事件库持续补充，未声称穷尽所有地方性事件。公告、发生和生效日分别解释；未核实发生时段的记录保留不确定性。筛选同时作用于总览图和事件列表。</p>
    </div>
    {!events.length ? <div className="study-empty"><h4>{board.events.length ? "没有匹配事件" : "事件时间轴已就绪"}</h4><p>{board.events.length ? "尝试清除筛选或更换年份、地区和关键词。" : "添加真实事件后，这里将显示时间轴、K 线标记和多资产窗口对照。"}</p><div className="study-event-flow"><span>事件与来源</span><span>→</span><span>价格时间轴</span><span>→</span><span>多资产变化</span><span>→</span><span>验证机制</span></div></div> : <div className="study-geo-layout"><aside className="study-event-list" aria-label="已标记事件">{events.map(e => <button key={e.id} aria-pressed={event?.id === e.id} onClick={() => chooseEvent(e)}><time>{e.date}</time><strong>{e.title}</strong><span>{CATEGORIES[e.category]} · {e.region || "地区待补充"}</span></button>)}</aside><div className="study-panel study-event-detail" ref={detailRef}>{event && <><div className="content-heading"><div><h3>{event.title}</h3><p className="muted">{event.date} · {event.region} · {CATEGORIES[event.category]}</p></div><div className="study-actions"><button className="text-button" onClick={() => setEdit(event)}>编辑</button><button className="text-button" disabled={busy} onClick={async () => { setBusy(true); try { await writeJson(`/api/research/board/events/${event.id}`, "DELETE"); await reload(); setNotice("事件已归档，原记录仍保留在数据库。"); } catch (e) { setError(e instanceof Error ? e.message : "归档失败"); } finally { setBusy(false); } }}>归档</button></div></div><div className="journal-evidence"><div><h4>事件事实</h4><p>{event.facts}</p></div><div><h4>可能机制 · 待验证</h4><p>{event.mechanism || "尚未记录传导机制。"}</p></div></div><ResearchSources sources={event.sources} sourceUrl={event.sourceUrl} />
      <div className="study-toolbar"><label>查看资产<select aria-label="事件图表资产" value={selectedChartId} onChange={e => setChartId(e.target.value)}>{comparisons.map(id => <option key={id} value={id}>{STUDY_INSTRUMENTS.find(i => i.id === id)!.name}</option>)}</select></label><button className="secondary-button" disabled={!!study.busy.length} onClick={() => void study.load(selectedChartId)}>{study.busy.includes(selectedChartId) ? "读取中…" : "重新读取当前资产"}</button><button className="secondary-button" disabled={!retryIds.length || !!study.busy.length || counts.pending > 0} onClick={() => void loadEvent()}>重试未就绪资产</button></div>
      <p className="study-event-load-status chart-note" role="status">已自动关联 {comparisons.length} 项历史资产 · 就绪 {counts.ready}/{comparisons.length}{counts.loading > 0 && ` · 正在读取 ${counts.loading} 项`}{counts.pending > 0 && ` · 等待 ${counts.pending} 项`}{counts.error > 0 && ` · 读取失败 ${counts.error} 项`}{counts.empty > 0 && ` · 暂无数据 ${counts.empty} 项`}。切换事件自动补齐，已读取历史直接复用。</p>
      {comparisons.filter(id => study.errors[id]).map(id => <p className="inline-error" role="alert" key={id}>{STUDY_INSTRUMENTS.find(i => i.id === id)!.name}：{study.errors[id]}</p>)}
      <StudyCandles key={`${event.id}-${selectedChartId}`} instrument={instrument} series={study.data[selectedChartId]} emptyMessage={emptyMessage(selectedChartId)} from={shift(event.date, -90)} through={shift(event.date, 120)} events={events} onEvent={e => setSelected(e.id)} onMark={date => setEdit({ date, assetIds: [selectedChartId], timing: "unknown", category: "war" })} />
      <h4>事件窗口对照</h4><p className="chart-note">五个美股指数作为统一时间对照；其他资产来自事件的关联资产记录，历史自动读取。缺少有效观测时保留为空。</p><div className="study-table-scroll"><table className="study-event-table"><thead><tr><th>资产 / 单位</th><th>基准 → 首个响应日</th><th>事前 5 期</th>{[1, 5, 20, 60].map(n => <th key={n}>事后 {n} 期</th>)}</tr></thead><tbody>{comparisons.map(id => { const item = STUDY_INSTRUMENTS.find(i => i.id === id)!, rate = item.kind === "rate", window = studyEventWindow(study.data[id]?.bars ?? [], event, rate); return <tr key={id} data-history-state={historyState(id)}><th>{item.name}<small>{rate ? "利率变动 · bp" : "价格涨跌 · %"}</small><small>{historyLabel(id)}</small></th><td>{window.baseDate ?? "—"}<small>→ {window.reactionDate ?? "—"}</small></td><td>{changeText(window.before5, rate ? " bp" : "%")}</td>{window.after.map(p => <td key={p.sessions}>{changeText(p.value, rate ? " bp" : "%")}<small>{p.date ?? (study.data[id] ? "观测不足" : historyLabel(id))}</small></td>)}</tr>; })}</tbody></table></div><p className="chart-note">{event.timing === "unknown" ? "发生时段尚未核实：暂从事件当日或其后首个观测日计算，收盘后发生的事件请修正时段。" : event.timing === "after-close" ? "收盘后事件从其后首个观测日计算。" : "从事件当日或其后首个观测日计算。"}基准是响应日前最后收盘；期数表示各来源有效观测数，日历与市场交易时段可能不同，表中列出实际日期。缺少历史或后续记录留空。</p><p className="study-warning">这些是事件附近的市场变化。同期政策、财报与其他冲击也可能影响价格，仅凭前后涨跌不能认定因果。</p></>}</div></div>}
  </div>;
}
