import { useMemo, useState } from "react";
import { aggregateStudyBars, monthObservation, seasonality, studyEventMarkers, type GeoEvent, type StudyInstrument, type StudySeries } from "@invest/domain";

export const STUDY_COLORS = ["#68b9ed", "#f4c36a", "#a799ef", "#70d1bc", "#ed97b2", "#90bc7e", "#e39464", "#6ed1dd", "#bbad8b", "#e8a7e6"];
export const changeText = (v: number | null | undefined, unit = "%") => v == null || !Number.isFinite(v) ? "—" : `${v > 0 ? "+" : ""}${v.toFixed(2)}${unit}`;
const valueText = (v: number) => v.toLocaleString("en-US", { maximumFractionDigits: 2 });
export interface PlotLine { id: string; name: string; color: string; points: { x: number; y: number | null }[] }
export function StudyLines({ lines, unit, calendar = true, label, cursor, onCursor }: { lines: PlotLine[]; unit: string; calendar?: boolean; label: string; cursor?: number | null; onCursor?: (x: number | null) => void }) {
  const [hover, setHover] = useState<number | null>(null);
  const all = lines.flatMap(l => l.points.filter(p => p.y !== null && Number.isFinite(p.y)));
  if (!all.length) return <p className="empty-state">加载有共同观测日期的历史后显示对照图。</p>;
  const minX = Math.min(...all.map(p => p.x)), maxX = Math.max(...all.map(p => p.x));
  const rawMin = Math.min(0, ...all.map(p => p.y!)), rawMax = Math.max(0, ...all.map(p => p.y!)), pad = (rawMax - rawMin || 1) * .08;
  const low = rawMin - pad, high = rawMax + pad;
  const x = (v: number) => 64 + (v - minX) / (maxX - minX || 1) * 790, y = (v: number) => 214 - (v - low) / (high - low) * 188;
  const xs = [...new Set(all.map(p => p.x))].sort((a, b) => a - b);
  const active = cursor === undefined ? hover : cursor;
  const focus = active === null ? xs.at(-1)! : xs.reduce((best, v) => Math.abs(v - active) < Math.abs(best - active) ? v : best, xs[0]!);
  const move = (v: number | null) => { setHover(v); onCursor?.(v); };
  const labelX = (v: number) => calendar ? new Date(v).toISOString().slice(0, 10) : `${v} 日`;
  return <div className="study-plot"><svg viewBox="0 0 880 250" role="img" aria-label={label} onPointerMove={e => { const r = e.currentTarget.getBoundingClientRect(); move(minX + ((e.clientX - r.left) / r.width * 880 - 64) / 790 * (maxX - minX)); }} onPointerLeave={() => move(null)}>
    {[0, 1, 2, 3, 4].map(i => { const v = low + (high - low) * i / 4; return <g key={i}><line x1="64" x2="854" y1={y(v)} y2={y(v)} className="study-gridline" /><text x="57" y={y(v) + 4} textAnchor="end">{v.toFixed(1)}</text></g>; })}
    <line x1="64" x2="854" y1={y(0)} y2={y(0)} className="study-zero" />
    {lines.map(l => { let pen = false; const path = l.points.map(p => { if (p.y === null || !Number.isFinite(p.y)) { pen = false; return ""; } const command = pen ? "L" : "M"; pen = true; return `${command}${x(p.x).toFixed(2)},${y(p.y).toFixed(2)}`; }).join(" "); return <path key={l.id} d={path} stroke={l.color} fill="none" strokeWidth="1.7" vectorEffect="non-scaling-stroke" />; })}
    <line x1={x(focus)} x2={x(focus)} y1="24" y2="215" className="study-crosshair" />
    {[minX, (maxX + minX) / 2, maxX].map((v, i) => <text key={i} x={x(v)} y="239" textAnchor={i === 0 ? "start" : i === 2 ? "end" : "middle"}>{labelX(calendar ? v : Math.round(v))}</text>)}
  </svg><div className="study-legend"><strong>{labelX(focus)}</strong>{lines.map(l => <span key={l.id} style={{ color: l.color }}>{l.name} {changeText(l.points.find(p => p.x === focus)?.y, unit)}</span>)}</div><label className="study-scrubber">查看观测日期<input aria-label={`${label}观测日期`} type="range" min={0} max={xs.length - 1} value={xs.indexOf(focus)} onChange={e => move(xs[Number(e.target.value)]!)} /></label></div>;
}

export function StudyCandles({ series, instrument, from, through, events = [], onMark, onEvent, initialInterval = "day", initialCount = 120, emptyMessage }: { series?: StudySeries; instrument: StudyInstrument; from: string; through: string; events?: GeoEvent[]; onMark?: (date: string) => void; onEvent?: (event: GeoEvent) => void; initialInterval?: "day" | "week" | "month"; initialCount?: number; emptyMessage?: string }) {
  const [interval, setInterval] = useState<"day" | "week" | "month">(initialInterval), [count, setCount] = useState(initialCount), [end, setEnd] = useState<number | null>(null), [hover, setHover] = useState<number | null>(null), [marking, setMarking] = useState(false);
  const [markerChoice, setMarkerChoice] = useState<string | null>(null);
  const filtered = useMemo(() => series?.bars.filter(b => b.date >= from && b.date <= through) ?? [], [series, from, through]);
  const bars = useMemo(() => aggregateStudyBars(filtered, interval), [filtered, interval]);
  const length = Math.min(count, bars.length), endpoint = Math.max(length, Math.min(end ?? bars.length, bars.length));
  const visible = bars.slice(endpoint - length, endpoint), current = visible[Math.min(hover ?? visible.length - 1, visible.length - 1)];
  const markers = useMemo(() => studyEventMarkers(series?.bars ?? [], bars, events, instrument.id, endpoint - length, endpoint, filtered.at(-1)?.date ?? ""), [series, bars, events, instrument.id, endpoint, length, filtered]);
  const groups = useMemo(() => [...new Set(markers.map(m => m.i))].map(i => ({ i, key: visible[i]!.date, items: markers.filter(m => m.i === i) })), [markers, visible]);
  const choice = groups.find(g => g.key === markerChoice);
  if (!series) return <div className="study-empty"><h4>{emptyMessage ? `${instrument.name}历史` : "选择一个基准，开始历史复盘"}</h4><p>{emptyMessage ?? "点击“加载历史”读取日度数据，再切换周期、比较资产变化或标记事件。"}</p></div>;
  if (!visible.length) return <p className="empty-state">所选时间范围内没有可用记录。来源覆盖 {series.from} 至 {series.through}。</p>;
  const lowRaw = Math.min(...visible.map(b => b.low ?? b.close)), highRaw = Math.max(...visible.map(b => b.high ?? b.close));
  const padding = (highRaw - lowRaw || Math.abs(highRaw) || 1) * .07, low = lowRaw - padding, high = highRaw + padding;
  const x = (i: number) => 72 + (i + .5) / visible.length * 774, y = (v: number) => 258 - (v - low) / (high - low) * 216;
  const nearest = (e: React.PointerEvent<SVGSVGElement> | React.MouseEvent<SVGSVGElement>) => { const r = e.currentTarget.getBoundingClientRect(); return Math.max(0, Math.min(visible.length - 1, Math.floor(((e.clientX - r.left) / r.width * 880 - 72) / 774 * visible.length))); };
  const csv = () => { const text = ["date,open,high,low,close", ...filtered.map(b => [b.date, b.open ?? "", b.high ?? "", b.low ?? "", b.close].join(","))].join("\n"); const url = URL.createObjectURL(new Blob([text], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `${instrument.id}-${from}-${through}.csv`; a.click(); URL.revokeObjectURL(url); };
  return <div className="study-chart"><div className="study-toolbar"><div className="segmented-control" aria-label="研究图表周期">{(["day", "week", "month"] as const).map((v, i) => <button key={v} aria-pressed={interval === v} onClick={() => { setInterval(v); setEnd(null); setHover(null); }}>{["日", "周", "月"][i]}{instrument.kind === "rate" || instrument.kind === "spot" ? "线" : " K"}</button>)}</div><span>{instrument.name} · {instrument.unit}</span><div>{onMark && <button className="secondary-button" aria-pressed={marking} onClick={() => setMarking(!marking)}>{marking ? "点击图中日期添加事件" : "＋ 在图上标记事件"}</button>} <button className="text-button" onClick={csv}>导出 CSV</button></div></div>
    {current && <div className="study-ohlc"><strong>{current.date}</strong>{current.open !== undefined && <><span>开 {valueText(current.open)}</span><span>高 {valueText(current.high!)}</span><span>低 {valueText(current.low!)}</span></>}<span>{current.open === undefined ? "观测" : "收"} {valueText(current.close)}</span>{interval !== "day" && <small>按周期首个有效日期标记</small>}</div>}
    <div className="study-chart-plot" tabIndex={0} role="region" aria-label={`${instrument.name}可滚动历史图`}><svg viewBox="0 0 880 296" role="img" aria-label={`${instrument.name}历史${instrument.kind === "rate" || instrument.kind === "spot" ? "折线" : "K 线"}图`} className={marking ? "study-marking" : ""} onPointerMove={e => setHover(nearest(e))} onPointerLeave={() => setHover(null)} onClick={e => { if (marking) { onMark?.(visible[nearest(e)]!.date); setMarking(false); } }}>
      {[0, 1, 2, 3, 4].map(i => { const v = low + (high - low) * i / 4; return <g key={i}><line x1="72" x2="846" y1={y(v)} y2={y(v)} className="study-gridline" /><text x="65" y={y(v) + 4} textAnchor="end">{valueText(v)}</text></g>; })}
      {visible.every(b => b.open !== undefined) ? visible.map((b, i) => { const color = b.close >= b.open! ? "#6bc7a0" : "#ee8d95"; return <g key={b.date}><line x1={x(i)} x2={x(i)} y1={y(b.high!)} y2={y(b.low!)} stroke={color} /><rect x={x(i) - Math.max(1, 774 / visible.length * .65) / 2} y={Math.min(y(b.open!), y(b.close))} width={Math.max(1, 774 / visible.length * .65)} height={Math.max(1, Math.abs(y(b.open!) - y(b.close)))} fill={color} /></g>; }) : <path d={visible.map((b, i) => `${i ? "L" : "M"}${x(i)},${y(b.close)}`).join(" ")} stroke="#68b9ed" strokeWidth="2" fill="none" />}
      {groups.map(({ key, items, i }, index) => { const activate = () => { if (items.length === 1) onEvent?.(items[0]!.event); else setMarkerChoice(key === markerChoice ? null : key); }; const label = items.length === 1 ? `${items[0]!.event.date} ${items[0]!.event.title}` : `${key} ${items.length} 条事件`; return <g key={key} role="button" tabIndex={0} aria-label={label} onClick={e => { e.stopPropagation(); activate(); }} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); activate(); } }} className="study-event-marker"><title>{label}</title><line x1={x(i)} x2={x(i)} y1="42" y2="258" /><circle cx={x(i)} cy={9 + index % 3 * 13} r={items.length > 1 ? 7 : 4} />{items.length > 1 && <text x={x(i)} y={13 + index % 3 * 13} textAnchor="middle">{items.length}</text>}</g>; })}
      {current && <line x1={x(visible.indexOf(current))} x2={x(visible.indexOf(current))} y1="40" y2="258" className="study-crosshair" />}
      {[0, Math.floor((visible.length - 1) / 2), visible.length - 1].map((i, j) => <text key={j} x={x(i)} y="282" textAnchor={j === 0 ? "start" : j === 2 ? "end" : "middle"}>{visible[i]!.date}</text>)}
    </svg></div><p className="study-chart-scroll-hint chart-note">横向滑动查看完整图表，也可按年份缩小范围。</p>
    <div className="study-toolbar study-ranges"><label>显示 {length} 条<input aria-label="研究图显示数量" type="range" min={Math.min(20, bars.length)} max={Math.min(500, bars.length)} value={length} onChange={e => { setCount(Number(e.target.value)); setHover(null); }} /></label><label>历史位置<input aria-label="研究图历史位置" type="range" min={length} max={bars.length} value={endpoint} onChange={e => { setEnd(Number(e.target.value)); setHover(null); }} /></label><button className="text-button" onClick={() => { setEnd(null); setHover(null); }}>回到末端</button></div>
    {marking && current && <button className="secondary-button" onClick={() => { onMark?.(current.date); setMarking(false); }}>在 {current.date} 添加事件</button>}
    {choice && <div className="study-marker-choice" aria-label="同一观测期的事件"><strong>{choice.key} · 选择事件</strong>{choice.items.map(({ event }) => <button className="text-button" key={event.id} onClick={() => { onEvent?.(event); setMarkerChoice(null); }}>{event.date} {event.title}</button>)}</div>}
    {!!markers.length && <details className="study-marker-list"><summary>图中 {markers.length} 条事件 · 同一观测期合并标记</summary><div className="study-legend">{markers.map(({ event, responseDate }) => <button className="text-button" key={event.id} onClick={() => onEvent?.(event)}>{event.date} {event.title}<small> → 观测 {responseDate}</small></button>)}</div></details>}
    <p className="chart-note">{series.source} · {series.priceBasis} · 有效范围 {series.from} — {series.through} · {series.bars.length} 条 · 采集 {new Date(series.fetchedAt).toLocaleString("zh-CN")}</p>
    {(series.stale || !!series.warnings.length) && <p className="study-warning" role="status">{[series.error, ...series.warnings].filter(Boolean).join(" ")}</p>}
    <details><summary>价格身份与来源</summary><p className="muted">{instrument.description}</p><a href={instrument.sourceUrl} target="_blank" rel="noreferrer">查看来源 ↗</a></details>
  </div>;
}

export function MonthlyStudy({ series }: { series?: StudySeries }) {
  const [month, setMonth] = useState(1), [hidden, setHidden] = useState<number[]>([]);
  const today = new Date().toISOString().slice(0, 10);
  const matrix = useMemo(() => seasonality(series?.bars ?? [], today), [series, today]);
  if (!series) return <div className="study-empty"><h4>十个完整年份，逐月对照</h4><p>加载指数历史后，显示月涨跌、上涨比例和同月走势。没有历史的格子会保留为空。</p></div>;
  const stats = Array.from({ length: 12 }, (_, i) => { const values = matrix.map(row => row[i]!.value).filter((v): v is number => v !== null).sort((a, b) => a - b), n = values.length; return { n, mean: n ? values.reduce((s, v) => s + v, 0) / n : null, median: n ? (values[Math.floor((n - 1) / 2)]! + values[Math.floor(n / 2)]!) / 2 : null, wins: n ? values.filter(v => v > 0).length / n * 100 : null }; });
  const paths = matrix.map((row, i) => { const obs = monthObservation(series.bars, row[0]!.year, month, today); return { id: String(obs.year), name: String(obs.year), color: STUDY_COLORS[i]!, points: obs.complete && obs.base && obs.base.close > 0 ? [{ x: 0, y: 0 }, ...obs.rows.map(b => ({ x: Number(b.date.slice(8)), y: (b.close / obs.base!.close - 1) * 100 }))] : [] }; });
  return <div className="monthly-study"><p className="muted">最近十个完整自然年 · 月末相对上月末的价格涨跌 · 点击月份比较各年路径</p><p className="chart-note">{series.source} · 覆盖 {series.from} — {series.through} · 采集 {new Date(series.fetchedAt).toLocaleString("zh-CN")}</p>{(series.stale || !!series.warnings.length) && <p className="study-warning" role="status">{[series.error, ...series.warnings].filter(Boolean).join(" ")}</p>}<div className="study-table-scroll"><table className="study-heatmap"><thead><tr><th>年份</th>{stats.map((_, i) => <th key={i}><button aria-pressed={month === i + 1} onClick={() => setMonth(i + 1)}>{i + 1} 月</button></th>)}</tr></thead><tbody>{matrix.map(row => <tr key={row[0]!.year}><th>{row[0]!.year}</th>{row.map(cell => <td key={cell.month} style={cell.value === null ? undefined : { background: cell.value >= 0 ? `rgba(69,176,126,${Math.min(.6, .08 + Math.abs(cell.value) / 20)})` : `rgba(220,99,113,${Math.min(.6, .08 + Math.abs(cell.value) / 20)})` }}><button onClick={() => setMonth(cell.month)} title={cell.value === null ? "来源覆盖不足，未计算" : `${cell.year} 年 ${cell.month} 月价格涨跌`}>{changeText(cell.value)}</button></td>)}</tr>)}{(["mean", "median", "wins", "n"] as const).map((field, i) => <tr key={field}><th>{["均值", "中位数", "上涨比例", "有效年份"][i]}</th>{stats.map((s, j) => <td key={j}>{field === "n" ? `${s.n}/10` : field === "wins" ? s.wins === null ? "—" : `${s.wins.toFixed(0)}%` : changeText(s[field])}</td>)}</tr>)}</tbody></table></div><div className="content-heading"><h4>{month} 月 · 各年份累计价格涨跌</h4><select aria-label="比较月份" value={month} onChange={e => setMonth(Number(e.target.value))}>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i + 1}>{i + 1} 月</option>)}</select></div><div className="study-year-select">{paths.map(p => <button key={p.id} style={{ color: p.color }} aria-pressed={!hidden.includes(Number(p.id))} onClick={() => setHidden(h => h.includes(Number(p.id)) ? h.filter(v => v !== Number(p.id)) : [...h, Number(p.id)])}>{p.name}{p.points.length ? "" : " · 缺失"}</button>)}</div><StudyLines label="同月跨年走势" calendar={false} unit="%" lines={paths.filter(p => !hidden.includes(Number(p.id)))} /><p className="chart-note">0 日代表上月末收盘，横轴为当月自然日；各年休市日不补价。月度边界不完整留空；异常历史间隔请结合来源提示核对。十个样本中的季节性不能单独作为择时结论，价格涨跌不含分红再投资。</p></div>;
}
