import { useMemo, useState } from "react";
import { RESEARCH_CLASSIFICATION, SECTORS, STUDY_INSTRUMENTS, type SectorId, type SectorNote, type StudyCompany } from "@invest/domain";
import { writeJson } from "./api";
import type { NewsItem } from "./types";
import type { StudyBoard, StudyData } from "./research-model";
import { StudyCandles } from "./ResearchCharts";

import { ResearchSources } from "./ResearchSources";

const NOTE_TYPES = { information: "关键信息", report: "研究报告", change: "行业变化", narrative: "公司叙事" } as const;
export function SectorObservation({ board, study, news, reload }: { board: StudyBoard; study: StudyData; news: NewsItem[]; reload: () => Promise<void> }) {
  const [sectorId, setSectorId] = useState<SectorId>("technology"), [cohort, setCohort] = useState<"established" | "emerging">("established");
  const [companyEdit, setCompanyEdit] = useState<Partial<StudyCompany> | null>(null), [noteEdit, setNoteEdit] = useState<Partial<SectorNote> | null>(null), [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [subsector, setSubsector] = useState(""), [companyQuery, setCompanyQuery] = useState(""), [theme, setTheme] = useState("");
  const sector = SECTORS.find(s => s.id === sectorId)!;
  const [benchmarkOverride, setBenchmarkOverride] = useState("");
  const benchmark = STUDY_INSTRUMENTS.find(i => i.id === ((sector.benchmarks as readonly string[]).includes(benchmarkOverride) ? benchmarkOverride : sector.benchmarks[0]))!;
  const companies = board.companies.filter(c => c.sector === sectorId && c.cohort === cohort);
  const matchesCompany = (c: StudyCompany) => (!subsector || c.subsector === subsector) && (!theme || c.tags?.includes(theme)) && `${c.symbol} ${c.name} ${c.narrative}`.toLowerCase().includes(companyQuery.toLowerCase());
  const filtered = !!(subsector || theme || companyQuery);
  const availableSubsectors = [...new Set(board.companies.filter(c => c.sector === sectorId).map(c => c.subsector).filter(Boolean))] as string[];
  const notes = board.notes.filter(n => n.sector === sectorId && `${n.title} ${n.body} ${n.symbol}`.toLowerCase().includes(query.toLowerCase()));
  const matched = useMemo(() => { const companyTerms = board.companies.filter(c => c.sector === sectorId).map(c => c.name.toLowerCase()); return news.filter(n => { const text = `${n.title} ${n.summary ?? ""}`.toLowerCase(); return [...sector.keywords, ...companyTerms].some(k => text.includes(k.toLowerCase())); }).slice(0, 20); }, [news, board.companies, sectorId, sector]);
  const save = async (type: "companies" | "notes", id: string | undefined, payload: unknown) => {
    if (busy) return; setBusy(true); setError(""); setNotice("");
    try { await writeJson(`/api/research/board/${type}${id ? `/${id}` : ""}`, id ? "PATCH" : "POST", payload); await reload(); if (type === "companies") setCompanyEdit(null); else setNoteEdit(null); setNotice("已保存到研究工作区。"); }
    catch (e) { setError(e instanceof Error ? e.message : "保存失败"); } finally { setBusy(false); }
  };
  const archive = async (type: "companies" | "notes", id: string) => { if (busy) return; setBusy(true); try { await writeJson(`/api/research/board/${type}/${id}`, "DELETE"); await reload(); setNotice("已归档，原记录仍保留在数据库。"); } catch (e) { setError(e instanceof Error ? e.message : "归档失败"); } finally { setBusy(false); } };
  const now = new Date().toISOString().slice(0, 10);
  return <div className="sector-observation"><details className="study-classification"><summary>分类口径与观察名单</summary><p>{RESEARCH_CLASSIFICATION.basis}</p><p>消费区分必需与可选；医疗包含药品、器械、诊断与服务；工业包含制造、航天与电气；材料包含矿业、钢铁与工业气体。铀等跨板块主题另加标签。成长组表示业务成长观察，包含资深企业的新业务及开发阶段项目。</p><a href={RESEARCH_CLASSIFICATION.sourceUrl} target="_blank" rel="noreferrer">GICS 分类方法 ↗</a></details><div className="study-sector-tabs" aria-label="行业类别">{SECTORS.map(s => <button key={s.id} aria-pressed={sectorId === s.id} onClick={() => { setSectorId(s.id); setBenchmarkOverride(""); setSubsector(""); setTheme(""); setCompanyQuery(""); }}><strong>{s.name}</strong><span>{board.companies.filter(c => c.sector === s.id).length} 家观察 · {board.notes.filter(n => n.sector === s.id).length} 条资料</span></button>)}</div>
    <div className="study-panel"><div className="content-heading"><div><h3>{sector.name} · 行业基准</h3><p className="muted">{sector.drivers}</p></div><div className="study-actions"><select aria-label="行业基准" value={benchmark.id} onChange={e => setBenchmarkOverride(e.target.value)}>{sector.benchmarks.map(id => <option key={id} value={id}>{STUDY_INSTRUMENTS.find(i => i.id === id)!.name}</option>)}</select><button className="secondary-button" disabled={!!study.busy.length} onClick={() => void study.load(benchmark.id)}>{study.busy.includes(benchmark.id) ? "读取中…" : "加载行业历史"}</button></div></div>{study.errors[benchmark.id] && <p className="inline-error" role="alert">{study.errors[benchmark.id]}</p>}<StudyCandles instrument={benchmark} series={study.data[benchmark.id]} from={`${new Date().getUTCFullYear() - 10}-01-01`} through={now} events={board.events} /></div>
    {error && <p className="inline-error" role="alert">{error}</p>}{notice && <p className="password-success" role="status">{notice}</p>}
    <div className="study-panel"><div className="content-heading"><div><h3>企业 Top 10 观察位</h3><p className="muted">每组 10 个研究优先级位置，覆盖代表性业务；不是市值或投资质量排名。叙事含研究推断，结合资料日期与验证指标阅读。</p></div><div className="segmented-control" aria-label="企业分组"><button aria-pressed={cohort === "established"} onClick={() => setCohort("established")}>成熟企业</button><button aria-pressed={cohort === "emerging"} onClick={() => setCohort("emerging")}>成长候选</button></div></div>
      {companyEdit && <form className="research-form study-editor" key={companyEdit.id ?? `${companyEdit.cohort}-${companyEdit.rank}`} onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void save("companies", companyEdit.id, { sector: f.get("sector"), cohort: f.get("cohort"), rank: Number(f.get("rank")), symbol: String(f.get("symbol")).trim().toUpperCase(), name: f.get("name"), narrative: f.get("narrative"), watch: f.get("watch"), sourceUrl: f.get("sourceUrl"), asOf: f.get("asOf"), subsector: f.get("subsector"), stage: f.get("stage"), tags: String(f.get("tags") ?? "").split(/[,，]/).map(t => t.trim()).filter(Boolean), sources: companyEdit.sources }); }}><h4 className="form-wide">{companyEdit.id ? "编辑" : "填充"}企业观察位</h4><label>行业<select name="sector" value={companyEdit.sector ?? sectorId} onChange={e => setCompanyEdit({ ...companyEdit, sector: e.target.value as SectorId })}>{SECTORS.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>组别<select name="cohort" defaultValue={companyEdit.cohort}><option value="established">成熟企业</option><option value="emerging">成长候选</option></select></label><label>观察位<input name="rank" type="number" min={1} max={10} defaultValue={companyEdit.rank} required /></label><label>股票代码<input name="symbol" maxLength={20} required defaultValue={companyEdit.symbol} placeholder="例如：公司交易代码" /></label><label>公司名称<input name="name" maxLength={150} required defaultValue={companyEdit.name} /></label><label>资料截至<input type="date" name="asOf" required defaultValue={companyEdit.asOf ?? now} /></label><label>细分行业<input name="subsector" maxLength={80} list="study-subsectors" defaultValue={companyEdit.subsector} /><datalist id="study-subsectors">{RESEARCH_CLASSIFICATION.sectors[companyEdit.sector ?? sectorId].map(s => <option key={s} value={s} />)}</datalist></label><label>业务阶段<input name="stage" maxLength={80} defaultValue={companyEdit.stage} placeholder="如：商业化扩张 / 开发阶段" /></label><label className="form-wide">主题标签（逗号分隔，最多 8 个）<input name="tags" defaultValue={companyEdit.tags?.join("，")} placeholder="半导体，存储" /></label><label className="form-wide">公司叙事 / 入选理由<textarea name="narrative" required maxLength={5000} defaultValue={companyEdit.narrative} placeholder="业务驱动力、竞争优势，以及它成为行业龙头的依据。" /></label><label className="form-wide">后续验证指标与风险<textarea name="watch" required maxLength={5000} defaultValue={companyEdit.watch} placeholder="下次财报要核对什么？什么证据会推翻叙事？" /></label><label className="form-wide">原始资料链接<input name="sourceUrl" type="url" maxLength={2000} defaultValue={companyEdit.sourceUrl} placeholder="公司 IR、年报或研究来源" /></label><div className="form-wide study-actions"><button className="primary-button" disabled={busy}>保存观察位</button><button type="button" className="secondary-button" onClick={() => setCompanyEdit(null)}>收起</button></div></form>}
      <div className="study-toolbar"><label>细分行业<select aria-label="细分行业筛选" value={subsector} onChange={e => setSubsector(e.target.value)}><option value="">全部细分</option>{availableSubsectors.map(s => <option key={s}>{s}</option>)}</select></label><label>查找企业<input aria-label="查找企业" value={companyQuery} onChange={e => setCompanyQuery(e.target.value)} placeholder="代码、名称或叙事" /></label>{sectorId === "technology" && <div className="segmented-control" aria-label="科技主题">{["", "半导体", "存储"].map(t => <button key={t} aria-pressed={theme === t} onClick={() => { setTheme(t); setSubsector(""); }}>{t || "全部主题"}</button>)}</div>}</div>
      {filtered && <p className="muted">当前组匹配 {companies.filter(matchesCompany).length} 家。编号保留原观察位；清除筛选可添加空位。</p>}
      <div className="study-company-grid">{Array.from({ length: 10 }, (_, i) => { const company = companies.find(c => c.rank === i + 1); if (filtered && (!company || !matchesCompany(company))) return null; return company ? <article key={i} className="study-company"><div className="content-heading"><span className="study-rank">{String(i + 1).padStart(2, "0")}</span><strong>{company.symbol}</strong><small>资料 {company.asOf}</small></div><h4>{company.name}</h4><div className="study-company-labels">{company.subsector && <span>{company.subsector}</span>}{company.stage && <span>{company.stage}</span>}{company.tags?.map(t => <span key={t}>{t}</span>)}</div><p>{company.narrative}</p><details><summary>验证指标与来源</summary><p>{company.watch}</p><ResearchSources sources={company.sources} sourceUrl={company.sourceUrl} /></details><div className="study-actions"><button className="text-button" onClick={() => setCompanyEdit(company)}>编辑</button><button className="text-button" disabled={busy} onClick={() => void archive("companies", company.id)}>归档</button></div></article> : <button key={i} className="study-company-slot" onClick={() => setCompanyEdit({ sector: sectorId, cohort, rank: i + 1 })}><span className="study-rank">{String(i + 1).padStart(2, "0")}</span><strong>＋ 添加{cohort === "established" ? "成熟企业" : "成长候选"}</strong><small>记录叙事 · 来源 · 验证指标</small></button>; })}</div><p className="chart-note">成长候选表示待研究的潜在龙头，加入观察位不代表已完成质量认证。观察位可按研究进展调整，优先保留可核对的来源与证伪指标。</p></div>
    <div className="study-panel"><div className="content-heading"><div><h3>资料与行业变化</h3><p className="muted">关键信息、报告、变化与叙事按时间保留。</p></div><button className="primary-button" onClick={() => setNoteEdit({ sector: sectorId, type: "information" })}>＋ 添加资料</button></div>
      {noteEdit && <form className="research-form study-editor" key={noteEdit.id ?? `${noteEdit.sector}-${noteEdit.title ?? "new"}`} onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void save("notes", noteEdit.id, { sector: f.get("sector"), type: f.get("type"), title: f.get("title"), date: f.get("date"), body: f.get("body"), sourceUrl: f.get("sourceUrl"), symbol: String(f.get("symbol")).trim().toUpperCase(), sources: noteEdit.sources, subsector: noteEdit.subsector, tags: noteEdit.tags }); }}><label>行业<select name="sector" defaultValue={noteEdit.sector}>{SECTORS.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>资料类型<select name="type" defaultValue={noteEdit.type}>{Object.entries(NOTE_TYPES).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label className="form-wide">标题<input name="title" required maxLength={200} defaultValue={noteEdit.title} /></label><label>日期<input type="date" name="date" required defaultValue={noteEdit.date ?? now} /></label><label>公司代码（可选）<input name="symbol" maxLength={20} defaultValue={noteEdit.symbol} /></label><label className="form-wide">内容 / 变化 / 待验证问题<textarea name="body" required maxLength={12000} defaultValue={noteEdit.body} /></label><label className="form-wide">来源链接<input type="url" name="sourceUrl" maxLength={2000} defaultValue={noteEdit.sourceUrl} /></label><div className="form-wide study-actions"><button className="primary-button" disabled={busy}>保存资料</button><button type="button" className="secondary-button" onClick={() => setNoteEdit(null)}>收起</button></div></form>}
      <input className="study-search" aria-label="检索行业资料" value={query} onChange={e => setQuery(e.target.value)} placeholder="检索已保存的标题、内容与公司代码…" />
      {notes.length ? <div className="study-notes">{notes.sort((a, b) => b.date.localeCompare(a.date)).map(n => <article key={n.id}><div className="news-meta"><span>{NOTE_TYPES[n.type]}</span><time>{n.date}</time><span>{n.symbol}</span></div><h4>{n.title}</h4><p>{n.body}</p><ResearchSources sources={n.sources} sourceUrl={n.sourceUrl} /><div className="study-actions"><button className="text-button" onClick={() => setNoteEdit(n)}>编辑</button><button className="text-button" disabled={busy} onClick={() => void archive("notes", n.id)}>归档</button></div></article>)}</div> : <p className="empty-state">暂无匹配资料。可手工添加报告链接与摘记，或从下方情报建立记录。</p>}
      <details className="study-matched-news"><summary>自动匹配已采集情报 · {matched.length} 条</summary><p className="muted">按行业关键词与观察公司名称匹配最近已采集新闻，相关性待核实；可先编辑再保存为资料。</p>{matched.map(n => <article key={n.id}><span className="muted">{n.sourceId} · {(n.publishedAt ?? n.fetchedAt).slice(0, 10)}</span><a href={n.url} target="_blank" rel="noreferrer">{n.title} ↗</a><button className="text-button" onClick={() => setNoteEdit({ sector: sectorId, title: n.title.slice(0, 200), date: (n.publishedAt ?? n.fetchedAt).slice(0, 10), sourceUrl: n.url, body: n.summary ?? n.title, type: "information" })}>整理为行业资料</button></article>)}{!matched.length && <p className="empty-state">当前已采集情报暂无匹配项。</p>}</details></div>
  </div>;
}
