import { useMemo, useState } from "react";
import { Decimal } from "decimal.js";
import { weeklyReviewMetrics, weeklyTradeTimeline, type TradingCase, type WeeklyReview, type WeeklyReviewInput, type ReviewFill } from "@invest/domain";
import { BrokerTradeTimeline } from "./BrokerTradeTimeline";
import { CHART_COLORS } from "./PortfolioCharts";
import { formatMoney, formatTimestamp } from "./format";
import { clearLocalDraft, draftTime, readLocalDraft, useLocalDraft } from "./useLocalDraft";
const WEEKLY_DRAFT_KEY = "invest:weekly-draft";
const timezone = () => Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
const localDay = (d: Date) => new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10);
function defaults(): WeeklyReviewInput { const today = new Date(), monday = new Date(today); monday.setDate(today.getDate() - (today.getDay() + 6) % 7); return { weekStart: localDay(monday), weekEnd: localDay(today), timezone: timezone(), goodCaseId: null, mistakeCaseId: null, riskyWinCaseId: null, findings: "", nextTrigger: "", nextAction: "", nextCheck: "", macroStudy: "", upcomingEvents: "", reading: "", englishTerms: "", recovery: "", marketImpact: "", opportunities: "", keyEvents: [] }; }
function dateInput(value: string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
export function WeeklyReviewWorkspace({ cases, fills, weekly, save, busy }: { cases: TradingCase[]; fills: ReviewFill[]; weekly: WeeklyReview[]; save: (path: string, body: unknown) => Promise<boolean>; busy: boolean }) {
  // The long weekly form is mirrored to this browser until it is saved, so leaving the tab does not lose it.
  const [restoredAt, setRestoredAt] = useState<string | null>(() => readLocalDraft<WeeklyReviewInput>(WEEKLY_DRAFT_KEY)?.savedAt ?? null);
  const [draft, setDraft] = useState<WeeklyReviewInput>(() => readLocalDraft<WeeklyReviewInput>(WEEKLY_DRAFT_KEY)?.value ?? defaults());
  const [selected, setSelected] = useState("");
  useLocalDraft(WEEKLY_DRAFT_KEY, draft, !selected);
  const [chartSource, setChartSource] = useState("cases");
  const saved = weekly.find(w => w.id === selected);
  const range = saved ?? draft;
  const chartCases = saved?.caseSnapshots ?? cases;
  const metrics = useMemo(() => { try { return saved?.metrics ?? weeklyReviewMetrics(cases, draft); } catch { return null; } }, [saved, cases, draft]);
  return <div className="tr-weekly"><div className="content-heading"><div><p className="eyebrow">WEEKLY TRADES & MACRO</p><h3>本周成交与宏观复盘</h3></div><select aria-label="查看历史周报" value={selected} onChange={e => setSelected(e.target.value)}><option value="">填写本次周报</option>{weekly.map(w => <option key={w.id} value={w.id}>{w.weekStart} — {w.weekEnd} · {formatTimestamp(w.recordedAt)}</option>)}</select></div>
    {!saved && <div className="filter-toolbar"><label>周报开始日期<input aria-label="周报开始日期" type="date" value={draft.weekStart} onChange={e => setDraft({ ...draft, weekStart: e.target.value })} /></label><label>周报结束日期<input aria-label="周报结束日期" type="date" min={draft.weekStart} value={draft.weekEnd} onChange={e => setDraft({ ...draft, weekEnd: e.target.value })} /></label><label>统计时区<input aria-label="统计时区" value={draft.timezone} onChange={e => setDraft({ ...draft, timezone: e.target.value })} /></label></div>}
    {saved && <p className="tr-notice">留存周报 · {saved.weekStart} 至 {saved.weekEnd} · {saved.timezone} · 图表采用保存时的成交快照。</p>}
    {!saved && restoredAt && <p className="tr-notice">已恢复 {draftTime(restoredAt)} 在本机未保存的周报草稿。<button type="button" className="text-button" onClick={() => { clearLocalDraft(WEEKLY_DRAFT_KEY); setDraft(defaults()); setRestoredAt(null); }}>放弃本机草稿</button></p>}
    <div className="tr-tabs" role="tablist" aria-label="周报图表数据"><button role="tab" aria-selected={chartSource === "cases"} onClick={() => setChartSource("cases")}>复盘档案收益</button><button role="tab" aria-selected={chartSource === "brokers"} onClick={() => setChartSource("brokers")}>券商原始成交</button></div>
    {chartSource === "cases" ? <WeeklyTradeChart cases={chartCases} range={range} /> : <BrokerTradeTimeline fills={saved ? saved.brokerFills ?? [] : fills} range={range} />}
    {metrics && <details className="tr-data-notes"><summary>交易统计与口径 · 本期完整退出 {metrics.closedCaseIds.length} 笔</summary><div className="position-table-wrap"><table className="position-table"><thead><tr><th>策略 / 币种</th><th>完整退出</th><th>净盈亏</th><th>胜 / 负 / 平</th><th>胜率</th></tr></thead><tbody>{metrics.groups.map((g, i) => <tr key={i}><td>{g.strategy} · {g.currency}</td><td>{g.completed}</td><td>{formatMoney(g.netPnl)}</td><td>{g.wins} / {g.losses} / {g.flat}</td><td>{formatMoney(g.winRate)}%</td></tr>)}</tbody></table></div>{metrics.missing.map(m => <p key={m}>{m}</p>)}</details>}
    {saved ? <article className="tr-surface macro-weekly"><h3>宏观周报</h3>{[["本周主要宏观变化", saved.findings], ["对市场的影响", saved.marketImpact], ["下周潜在交易机会", saved.opportunities], ["主要证据与来源", saved.macroStudy]].map(([label, value]) => <section key={label}><h4>{label}</h4><p className="tr-prose">{value || "未记录"}</p></section>)}<h4>下周关键事件</h4><div className="macro-event-timeline">{(saved.keyEvents ?? []).map((event, i) => <article key={i}><time>{event.scheduledAt ? formatTimestamp(event.scheduledAt) : "时间待定"}</time><strong>{event.title}</strong><p>{event.impact}</p>{event.sourceUrl && <a href={event.sourceUrl} target="_blank" rel="noreferrer">事件来源 ↗</a>}<small>原记录时区：{event.timezone}</small></article>)}</div>{saved.upcomingEvents && <p className="tr-prose">{saved.upcomingEvents}</p>}{[saved.nextAction, saved.reading, saved.englishTerms, saved.recovery].some(Boolean) && <details><summary>历史补充记录</summary><p>{saved.nextTrigger} · {saved.nextAction} · {saved.nextCheck}</p><p>{saved.reading}</p><p>{saved.englishTerms}</p><p>{saved.recovery}</p></details>}<button className="secondary-button" onClick={() => { const link = document.createElement('a'), blob = URL.createObjectURL(new Blob([JSON.stringify(saved, null, 2)], { type: 'application/json' })); link.href = blob; link.download = `macro-weekly-${saved.weekStart}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(blob), 1000); }}>导出本次周报</button></article> : <form className="tr-surface tr-form macro-weekly" onSubmit={async e => { e.preventDefault(); if (await save('/api/trading-review/weekly', draft)) { clearLocalDraft(WEEKLY_DRAFT_KEY); setRestoredAt(null); setDraft(d => ({ ...d, findings: '', marketImpact: '', opportunities: '', macroStudy: '', keyEvents: [] })); } }}>
      <div className="tr-full"><h3>宏观周报</h3><p className="muted">记录事实、市场反应和条件判断，重点关注美债、黄金、原油与利率预期。</p></div>
      <label className="tr-full"><span>本周主要宏观变化</span><textarea required maxLength={10000} value={draft.findings} onChange={e => setDraft({ ...draft, findings: e.target.value })} placeholder="本周发生了什么？关键数据和政策预期怎样变化？" /></label>
      <label className="tr-full"><span>对市场的影响</span><textarea required maxLength={10000} value={draft.marketImpact} onChange={e => setDraft({ ...draft, marketImpact: e.target.value })} placeholder="事实 → 传导机制 → 美债 / 黄金 / 原油 / 股票的反应；区分已发生与个人推测" /></label>
      <label className="tr-full"><span>下周潜在交易机会</span><textarea required maxLength={10000} value={draft.opportunities} onChange={e => setDraft({ ...draft, opportunities: e.target.value })} placeholder="关注标的与方向；什么条件出现才考虑交易？哪些变化会推翻判断？" /></label>
      <label className="tr-full"><span>主要证据与来源（可选）</span><textarea maxLength={10000} value={draft.macroStudy} onChange={e => setDraft({ ...draft, macroStudy: e.target.value })} placeholder="公告、数据、新闻链接及发布时间" /></label>
      <div className="tr-full macro-event-editor"><div className="tr-row"><h4>下周关键事件时间节点</h4><button type="button" className="secondary-button" onClick={() => setDraft({ ...draft, keyEvents: [...draft.keyEvents, { title: '', scheduledAt: null, timezone: timezone(), impact: '', sourceUrl: '' }] })}>＋ 添加关键事件</button></div>
        {draft.keyEvents.map((event, index) => { const update = (patch: Partial<typeof event>) => setDraft({ ...draft, keyEvents: draft.keyEvents.map((v, i) => i === index ? { ...v, ...patch } : v) }); return <fieldset key={index} className="macro-event-fields"><legend>事件 {index + 1}</legend><label><span>事件名称</span><input aria-label={`事件 ${index + 1} 名称`} required maxLength={200} value={event.title} onChange={e => update({ title: e.target.value })} /></label><label><span>发生时间 · {timezone()}（可留空）</span><input aria-label={`事件 ${index + 1} 时间`} type="datetime-local" value={dateInput(event.scheduledAt)} onChange={e => update({ scheduledAt: e.target.value ? new Date(e.target.value).toISOString() : null, timezone: timezone() })} /></label><label><span>潜在影响 / 观察点</span><textarea aria-label={`事件 ${index + 1} 影响`} value={event.impact} onChange={e => update({ impact: e.target.value })} /></label><label><span>来源链接</span><input aria-label={`事件 ${index + 1} 来源`} type="url" value={event.sourceUrl} onChange={e => update({ sourceUrl: e.target.value })} /></label><button type="button" className="text-button" onClick={() => setDraft({ ...draft, keyEvents: draft.keyEvents.filter((_, i) => i !== index) })}>移除此事件</button></fieldset>; })}
      </div><div className="tr-full"><button className="primary-button" disabled={busy}>保存本次周报快照</button></div>
    </form>}
  </div>;
}

function WeeklyTradeChart({ cases, range }: { cases: TradingCase[]; range: Pick<WeeklyReviewInput, 'weekStart' | 'weekEnd' | 'timezone'> }) {
  const [broker, setBroker] = useState('all'), [currency, setCurrency] = useState('USD'), [mode, setMode] = useState('cumulative'), [selected, setSelected] = useState('');
  const data = useMemo(() => { try { return weeklyTradeTimeline(cases, range); } catch { return { points: [], omitted: ['请检查日期与统计时区'] }; } }, [cases, range]);
  const currencies = [...new Set(data.points.map(p => p.currency))].sort();
  const unit = currencies.includes(currency) ? currency : currencies[0] ?? 'USD';
  const brokers = [...new Set(data.points.filter(p => p.currency === unit).map(p => p.broker))];
  const shown = brokers.filter(b => broker === 'all' || broker === b);
  const start = Date.parse(range.weekStart), end = Date.parse(range.weekEnd);
  const days = Number.isFinite(start) && Number.isFinite(end) && end >= start && end - start <= 6 * 86400000 ? Array.from({ length: Math.round((end - start) / 86400000) + 1 }, (_, i) => new Date(start + i * 86400000).toISOString().slice(0, 10)) : [];
  const series = shown.map(name => { let cumulative = new Decimal(0); return { name, points: days.map(day => { const point = data.points.find(p => p.broker === name && p.currency === unit && p.day === day); cumulative = cumulative.plus(point?.pnl ?? '0'); return { day, value: mode === 'cumulative' ? cumulative.toNumber() : Number(point?.pnl ?? 0), point }; }) }; });
  const values = series.flatMap(s => s.points.map(p => p.value)), min = Math.min(0, ...values), rawMax = Math.max(0, ...values), max = rawMax === min ? min + 1 : rawMax, span = max - min;
  const x = (i: number) => 62 + i * 690 / Math.max(1, days.length - 1), y = (value: number) => 225 - (value - min) / span * 178;
  const points = data.points.filter(p => p.currency === unit && (broker === 'all' || p.broker === broker));
  return <figure className="weekly-trade-chart portfolio-chart"><figcaption><div><h3>成交时间与已完成交易收益</h3><p className="chart-note">{range.weekStart} — {range.weekEnd} · {range.timezone}</p></div><div className="filter-toolbar"><select aria-label="收益图券商" value={broker} onChange={e => setBroker(e.target.value)}><option value="all">全部券商</option>{brokers.map(b => <option key={b}>{b}</option>)}</select><select aria-label="收益图币种" value={unit} onChange={e => setCurrency(e.target.value)}>{(currencies.length ? currencies : ['USD']).map(c => <option key={c}>{c}</option>)}</select><select aria-label="收益图方式" value={mode} onChange={e => setMode(e.target.value)}><option value="cumulative">周内累计净盈亏</option><option value="daily">每日净盈亏</option></select></div></figcaption>
    {points.length && days.length ? <><svg viewBox="0 0 800 280" role="img" aria-label={`按日期和券商的${mode === 'cumulative' ? '累计' : '每日'}净盈亏折线图，币种 ${unit}`}><text x="14" y="21" className="chart-axis-text">{unit}</text>{[min, min + span / 2, max || 1].map((value, i) => <g key={i}><line x1="62" x2="752" y1={y(value)} y2={y(value)} className="chart-grid-line" /><text x="55" y={y(value) + 4} textAnchor="end" className="chart-axis-text">{formatMoney(String(value))}</text></g>)}{days.map((day, i) => <text key={day} x={x(i)} y="255" textAnchor="middle" className="chart-axis-text">{day.slice(5)}</text>)}{series.map(s => <g key={s.name}><polyline fill="none" stroke={CHART_COLORS[brokers.indexOf(s.name) % CHART_COLORS.length]} strokeWidth="2.5" points={s.points.map((p, i) => `${x(i)},${y(p.value)}`).join(' ')} />{s.points.map((p, i) => <circle key={p.day} cx={x(i)} cy={y(p.value)} r={p.point?.fills ? 6 : 3} fill={CHART_COLORS[brokers.indexOf(s.name) % CHART_COLORS.length]} tabIndex={0} role="button" aria-label={`${p.day} ${s.name} ${formatMoney(String(p.value))} ${unit}，${p.point?.fills ?? 0} 笔成交`} onFocus={() => setSelected(`${p.day} ${s.name}`)} onClick={() => setSelected(`${p.day} ${s.name}`)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setSelected(`${p.day} ${s.name}`); } }}><title>{p.day} · {s.name} · {formatMoney(String(p.value))} {unit} · {p.point?.fills ?? 0} 笔成交 / {p.point?.completed ?? 0} 笔完整退出</title></circle>)}</g>)}</svg><div className="line-legend">{brokers.map((b, i) => <button type="button" key={b} aria-pressed={broker === b} onClick={() => setBroker(broker === b ? 'all' : b)}><i style={{ background: CHART_COLORS[i % CHART_COLORS.length] }} />{b}</button>)}</div><div className="position-table-wrap"><table className="position-table"><thead><tr><th>成交日期</th><th>券商</th><th>成交笔数</th><th>完整退出策略</th><th>当日净盈亏 · {unit}</th><th>策略</th></tr></thead><tbody>{points.map(p => <tr className={selected === `${p.day} ${p.broker}` ? 'chart-selected-row' : ''} key={`${p.day}:${p.broker}`}><td>{p.day}</td><td>{p.broker}</td><td>{p.fills}</td><td>{p.completed}</td><td>{formatMoney(p.pnl)}</td><td>{p.titles.join('、') || '未完整退出'}</td></tr>)}</tbody></table></div></> : <p className="empty-state">这周尚无可按日期统计的档案成交。可切换日期查看历史交易。</p>}
    <p className="chart-note">圆点对应成交日期；净盈亏仅计入已完整退出、字段齐全的复盘策略，已扣成交费用。部分平仓和浮盈亏未计入；现金流不作为收益。跨券商组合单独列示。</p>{data.omitted.map(note => <p className="chart-note" key={note}>{note}</p>)}
  </figure>;
}
